In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler

from sklearn.model_selection import train_test_split

In [2]:
test=pd.read_csv('test1.csv')  #loading dataset

In [3]:
test.head()

,patient_id,tumor_cell_count,gender,age_group,race,year_of_diagnosis,morphology_code,year_of_death,smoke_units,area_code,...,symptom57,symptom58,symptom59,symptom60,symptom61,symptom62,symptom63,symptom64,symptom65,symptom66
0,TCBA-B8-0x7e9,1,Male,85-89,White,2009,80003,2014.0,25,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,TCBA-B8-0x6bc,1,Male,80-84,White,2013,82503,2020.0,12,8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,TCBA-B8-0x1195,1,Male,60-64,White,2013,80703,2017.0,3,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,TCBA-B8-0x8a5,1,Male,85-89,White,2013,80103,2018.0,20,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,TCBA-B8-0xa21,1,Male,85-89,White,2009,80003,NaN,25,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
test.isna().sum()           #gives the number of missing values for each variable

patient_id            0
tumor_cell_count      0
gender                0
age_group            15
race                199
                   ...
symptom62             1
symptom63             1
symptom64             1
symptom65             1
symptom66             1
Length: 69, dtype: int64

In [29]:
test.dropna(how="any",axis=1)

,patient_id,tumor_cell_count,gender,year_of_diagnosis,morphology_code,smoke_units,area_code,alcohol_consume_units,symptoms
0,TCBA-B8-0x7e9,1,Male,2009,80003,25,4,4,Humira
1,TCBA-B8-0x6bc,1,Male,2013,82503,12,8,3,Sleeplessness
2,TCBA-B8-0x1195,1,Male,2013,80703,3,5,6,Back pain
3,TCBA-B8-0x8a5,1,Male,2013,80103,20,5,0,Depression
4,TCBA-B8-0xa21,1,Male,2009,80003,25,2,8,Neck pain
...,...,...,...,...,...,...,...,...,...
1964,TCBA-B8-0xc5f,1,Female,2010,82503,15,4,6,Polycystic Ovaries
1965,TCBA-B8-0x267,1,Male,2010,81403,3,2,3,Crying
1966,TCBA-B8-0xce9,1,Female,2013,81403,10,8,6,Sjogren's syndrome
1967,TCBA-B8-0xc20,1,Female,2013,80463,10,6,2,Polycystic Ovaries
1968,TCBA-B8-0x742,3,Female,2011,80103,34,2,8,Muscle cramps

In [31]:
test.isna().sum()

patient_id            0
tumor_cell_count      0
gender                0
age_group            15
race                199
                   ...
symptom62             1
symptom63             1
symptom64             1
symptom65             1
symptom66             1
Length: 69, dtype: int64

In [18]:
test.describe()

,tumor_cell_count,year_of_diagnosis,morphology_code,year_of_death,smoke_units,area_code,alcohol_consume_units,symptom1,symptom2,symptom3,...,symptom57,symptom58,symptom59,symptom60,symptom61,symptom62,symptom63,symptom64,symptom65,symptom66
count,1969.000000,1969.000000,1969.000000,1687.000000,1969.000000,1969.000000,1969.000000,1968.000000,1968.000000,1968.000000,...,1968.000000,1968.000000,1968.000000,1968.000000,1968.000000,1968.000000,1968.000000,1968.000000,1968.000000,1968.000000
mean,7.644997,2010.853225,80883.195023,2016.598103,14.791772,5.326562,3.295074,0.135163,0.022866,0.022358,...,0.021341,0.017785,0.021341,0.021850,0.025407,0.024898,0.024390,0.028455,0.027947,0.020833
std,23.119727,1.394054,1294.474641,1.773924,7.931638,2.456638,2.399988,0.341984,0.149514,0.147882,...,0.144557,0.132201,0.144557,0.146229,0.157396,0.155855,0.154297,0.166312,0.164863,0.142862
min,1.000000,2009.000000,80003.000000,2013.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,2010.000000,80103.000000,2015.000000,10.000000,3.000000,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,2011.000000,80463.000000,2017.000000,15.000000,5.000000,3.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,3.000000,2012.000000,81403.000000,2018.000000,20.000000,8.000000,5.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,413.000000,2013.000000,91333.000000,2020.000000,34.000000,10.000000,8.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [20]:
test.fillna(2017.000000)

,patient_id,tumor_cell_count,gender,age_group,race,year_of_diagnosis,morphology_code,year_of_death,smoke_units,area_code,...,symptom57,symptom58,symptom59,symptom60,symptom61,symptom62,symptom63,symptom64,symptom65,symptom66
0,TCBA-B8-0x7e9,1,Male,85-89,White,2009,80003,2014.0,25,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,TCBA-B8-0x6bc,1,Male,80-84,White,2013,82503,2020.0,12,8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,TCBA-B8-0x1195,1,Male,60-64,White,2013,80703,2017.0,3,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,TCBA-B8-0x8a5,1,Male,85-89,White,2013,80103,2018.0,20,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,TCBA-B8-0xa21,1,Male,85-89,White,2009,80003,2017.0,25,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1964,TCBA-B8-0xc5f,1,Female,70-74,White,2010,82503,2019.0,15,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1965,TCBA-B8-0x267,1,Male,75-79,White,2010,81403,2016.0,3,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1966,TCBA-B8-0xce9,1,Female,80-84,White,2013,81403,2018.0,10,8,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1967,TCBA-B8-0xc20,1,Female,50-54,OtherEth,2013,80463,2018.0,10,6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1968,TCBA-B8-0x742,3,Female,70-74,White,2011,80103,2016.0,34,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
train=pd.read_csv('train1.csv')  #loading dataset
train.head()

,patient_id,tumor_cell_count,gender,age_group,race,year_of_diagnosis,morphology_code,year_of_death,smoke_units,area_code,...,symptom58,symptom59,symptom60,symptom61,symptom62,symptom63,symptom64,symptom65,symptom66,death_due_to_cancer
0,TCBA-B8-0x204,7,Male,60-64,NaN,2010,81403,2016.0,34,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,TCBA-B8-0x1063,1,Male,85-89,White,2012,80463,2016.0,4,7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,TCBA-B8-0xb7d,1,Female,70-74,White,2013,80103,2018.0,20,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,TCBA-B8-0xfa7,104,Female,65-69,White,2013,80463,2018.0,20,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4,TCBA-B8-0xdc,21,Male,50-54,White,2010,80463,2016.0,20,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [5]:
sample_submission=pd.read_csv('sample_submission1.csv')  #loading dataset
sample_submission.head()

       patient_id  death_due_to_cancer
0   TCBA-B8-0x204                    1
1  TCBA-B8-0x1063                    1
2   TCBA-B8-0xb7d                    1
3   TCBA-B8-0xfa7                    1
4    TCBA-B8-0xdc                    1

In [6]:
#test.plot.scatter(x ='smoke_units', y ='death_due_to_cancer')

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=0)

### AdaBusting

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
model = AdaBoostClassifier(random_state=1)
model.fit(xtrain, ytrain)
model.score(xtest,ytest)

## By using Random Forest

In [7]:
#x=df.drop(columns=["Outcome"])
#y=df["Outcome"]

NameError: name 'df' is not defined

In [21]:
xtest=test
ytrain=train

In [22]:
#from sklearn.model_selection import train_test_split
#xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=0)

#### Bagging

In [23]:
#Bagging Meta Estimator Classifier
from sklearn.ensemble import BaggingClassifier
#making the bagging classifier with 100 decision trees
model=BaggingClassifier(n_estimators=100)
#fitting data to bagging model
model.fit(xtest,ytrain)
#testing on test dataset 
ypred=model.predict(xtest)
#Model Evaluation 
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print("accuracy is :",accuracy_score(ytest,ypred))
cm=confusion_matrix(ytest,ypred)
sns.heatmap(cm,annot=True)
print(classification_report(ytest,ypred))

ValueError: Input contains NaN